version: '3.8'

services:
  nextjs-app:
    build:
      context: .               # Specifies the build context (current directory)
      dockerfile: Dockerfile   # Optional if Dockerfile is named 'Dockerfile'
    container_name: nexamanga-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - API_URL=https://api.nexamanga.online
    networks:
      - app-network
    volumes:
      - ./nextjs-logs:/app/logs # Optional: To persist logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  app-network:
    driver: bridge
