name: สร้าง Docker Image และติดตั้ง

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    # สร้าง Docker Image
    - name: สร้าง Docker Image
      run: docker build -t sila030446/nexamanga:latest .
      
    # เข้าสู่ Docker Registry
    - name: เข้าสู่ Docker Registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    # อัปโหลด Docker Image ขึ้น Registry
    - name: อัปโหลด Docker Image
      run: docker push sila030446/nexamanga:latest
      
    # ติดตั้ง Docker Image บนเซิร์ฟเวอร์ภายในบ้าน
    - name: ติดตั้งบนเซิร์ฟเวอร์
      uses: appleboy/ssh-action@master
      with:
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        host: ${{ secrets.SSH_HOST }}
        script: |
          docker pull sila030446/nexamanga:latest
          docker stop nexamanga-app || true
          docker rm nexamanga-app || true
          docker run -d --name nexamanga-app --rm sila030446/nexamanga:latest
